### ISSUE TITLE
Workshop guide indicates that I should select a destination to which to clone the project, but CRW doesn't prompt me

### ISSUE THREAD

**Issue by andykrohg** [sshaaf/dg8-workshop#12]
CodeReady Workspaces does not present me with this screen
![image](https://user-images.githubusercontent.com/5431427/79577710-1d661a80-8093-11ea-9645-e2181e0ce840.png)

**Comment by danieloh30** [comment]
This will be only shown when you click on "Git Clone..." on the welcome page. Unfortunately, there's an issue to use that feature in CRW 2.1. We will update the instruction soon.
